import type { WeatherEffectsQuality } from "../types";

export interface WeatherQualityFlags {
  stars: boolean;
  motes: boolean;
  layeredClouds: boolean;
  frontCloudBank: boolean;
  deepOvercast: boolean;
  distantCurtains: boolean;
  texturedCurtains: boolean;
  glassOverlay: boolean;
  glassDroplets: boolean;
  frostOverlay: boolean;
  lightningForks: boolean;
  relightAnchors: boolean;
  horizonPoles: boolean;
  multiFlash: boolean;
}

export interface WeatherQualityBudget {
  resolutionScale: number;
  maxDevicePixelRatio: number;
  stars: number;
  motes: number;
  cloudLayers: number;
  cloudSprites: number;
  frontCloudSprites: number;
  fogWisps: number;
  frontMistWisps: number;
  anchorBands: number;
  scudLayers: number;
  shadowPasses: number;
  horizonGlowPasses: number;
  rainBack: number;
  rainFront: number;
  rainCurtains: number;
  curtainTextures: number;
  contactBands: number;
  impactBursts: number;
  runoffSheets: number;
  accumulationBands: number;
  condensationBlooms: number;
  fogCreepBands: number;
  shadowSweepPasses: number;
  distortionPasses: number;
  snowBack: number;
  snowFront: number;
  snowGusts: number;
  glassBeads: number;
  glassRivulets: number;
  lightningBranches: number;
  lightningForks: number;
  lightningGlow: number;
  flags: WeatherQualityFlags;
}

export const WEATHER_QUALITY_BUDGETS: Record<WeatherEffectsQuality, WeatherQualityBudget> = {
  performance: {
    resolutionScale: 0.85,
    maxDevicePixelRatio: 1.2,
    stars: 18,
    motes: 8,
    cloudLayers: 2,
    cloudSprites: 5,
    frontCloudSprites: 0,
    fogWisps: 4,
    frontMistWisps: 1,
    anchorBands: 1,
    scudLayers: 0,
    shadowPasses: 1,
    horizonGlowPasses: 1,
    rainBack: 90,
    rainFront: 160,
    rainCurtains: 2,
    curtainTextures: 1,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 0,
    snowBack: 56,
    snowFront: 96,
    snowGusts: 1,
    glassBeads: 0,
    glassRivulets: 0,
    lightningBranches: 1,
    lightningForks: 0,
    lightningGlow: 0.72,
    flags: {
      stars: true,
      motes: false,
      layeredClouds: false,
      frontCloudBank: false,
      deepOvercast: false,
      distantCurtains: true,
      texturedCurtains: false,
      glassOverlay: false,
      glassDroplets: false,
      frostOverlay: false,
      lightningForks: false,
      relightAnchors: false,
      horizonPoles: false,
      multiFlash: false,
    },
  },
  lite: {
    resolutionScale: 1,
    maxDevicePixelRatio: 1.45,
    stars: 34,
    motes: 16,
    cloudLayers: 3,
    cloudSprites: 8,
    frontCloudSprites: 2,
    fogWisps: 6,
    frontMistWisps: 2,
    anchorBands: 2,
    scudLayers: 1,
    shadowPasses: 2,
    horizonGlowPasses: 2,
    rainBack: 140,
    rainFront: 260,
    rainCurtains: 3,
    curtainTextures: 2,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 1,
    snowBack: 110,
    snowFront: 190,
    snowGusts: 2,
    glassBeads: 8,
    glassRivulets: 4,
    lightningBranches: 2,
    lightningForks: 1,
    lightningGlow: 0.86,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: false,
      deepOvercast: false,
      distantCurtains: true,
      texturedCurtains: true,
      glassOverlay: true,
      glassDroplets: false,
      frostOverlay: true,
      lightningForks: true,
      relightAnchors: true,
      horizonPoles: false,
      multiFlash: false,
    },
  },
  standard: {
    resolutionScale: 1.1,
    maxDevicePixelRatio: 1.8,
    stars: 64,
    motes: 28,
    cloudLayers: 4,
    cloudSprites: 12,
    frontCloudSprites: 4,
    fogWisps: 10,
    frontMistWisps: 4,
    anchorBands: 3,
    scudLayers: 2,
    shadowPasses: 3,
    horizonGlowPasses: 3,
    rainBack: 240,
    rainFront: 420,
    rainCurtains: 5,
    curtainTextures: 3,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 2,
    snowBack: 180,
    snowFront: 320,
    snowGusts: 3,
    glassBeads: 20,
    glassRivulets: 8,
    lightningBranches: 3,
    lightningForks: 2,
    lightningGlow: 1,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: true,
      deepOvercast: true,
      distantCurtains: true,
      texturedCurtains: true,
      glassOverlay: true,
      glassDroplets: true,
      frostOverlay: true,
      lightningForks: true,
      relightAnchors: true,
      horizonPoles: true,
      multiFlash: true,
    },
  },
  cinematic: {
    resolutionScale: 1.3,
    maxDevicePixelRatio: 2.25,
    stars: 112,
    motes: 44,
    cloudLayers: 6,
    cloudSprites: 18,
    frontCloudSprites: 7,
    fogWisps: 16,
    frontMistWisps: 7,
    anchorBands: 5,
    scudLayers: 3,
    shadowPasses: 5,
    horizonGlowPasses: 4,
    rainBack: 360,
    rainFront: 720,
    rainCurtains: 8,
    curtainTextures: 5,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 3,
    snowBack: 300,
    snowFront: 620,
    snowGusts: 5,
    glassBeads: 40,
    glassRivulets: 14,
    lightningBranches: 5,
    lightningForks: 4,
    lightningGlow: 1.22,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: true,
      deepOvercast: true,
      distantCurtains: true,
      texturedCurtains: true,
      glassOverlay: true,
      glassDroplets: true,
      frostOverlay: true,
      lightningForks: true,
      relightAnchors: true,
      horizonPoles: true,
      multiFlash: true,
    },
  },
};

export function getQualityBudget(quality: WeatherEffectsQuality): WeatherQualityBudget {
  return WEATHER_QUALITY_BUDGETS[quality];
}
