import type { WeatherEffectsQuality } from "../types";

export interface WeatherQualityFlags {
  stars: boolean;
  motes: boolean;
  layeredClouds: boolean;
  frontCloudBank: boolean;
  deepOvercast: boolean;
  distantCurtains: boolean;
  texturedCurtains: boolean;
  glassOverlay: boolean;
  glassDroplets: boolean;
  frostOverlay: boolean;
  lightningForks: boolean;
  relightAnchors: boolean;
  horizonPoles: boolean;
  multiFlash: boolean;
}

export interface WeatherQualityBudget {
  resolutionScale: number;
  maxDevicePixelRatio: number;
  maxPixelCount: number;
  frameIntervalMs: number;
  slowPassIntervalMs: number;
  stars: number;
  motes: number;
  cloudLayers: number;
  cloudSprites: number;
  frontCloudSprites: number;
  fogWisps: number;
  frontMistWisps: number;
  anchorBands: number;
  scudLayers: number;
  shadowPasses: number;
  horizonGlowPasses: number;
  rainBack: number;
  rainFront: number;
  rainCurtains: number;
  curtainTextures: number;
  contactBands: number;
  impactBursts: number;
  runoffSheets: number;
  accumulationBands: number;
  condensationBlooms: number;
  fogCreepBands: number;
  shadowSweepPasses: number;
  distortionPasses: number;
  snowBack: number;
  snowFront: number;
  snowGusts: number;
  glassBeads: number;
  glassRivulets: number;
  lightningBranches: number;
  lightningForks: number;
  lightningGlow: number;
  flags: WeatherQualityFlags;
}

export const WEATHER_QUALITY_BUDGETS: Record<WeatherEffectsQuality, WeatherQualityBudget> = {
  performance: {
    resolutionScale: 0.72,
    maxDevicePixelRatio: 1,
    maxPixelCount: 540_000,
    frameIntervalMs: 1000 / 24,
    slowPassIntervalMs: 250,
    stars: 10,
    motes: 0,
    cloudLayers: 1,
    cloudSprites: 3,
    frontCloudSprites: 0,
    fogWisps: 1,
    frontMistWisps: 0,
    anchorBands: 1,
    scudLayers: 0,
    shadowPasses: 1,
    horizonGlowPasses: 1,
    rainBack: 24,
    rainFront: 16,
    rainCurtains: 0,
    curtainTextures: 0,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 0,
    snowBack: 20,
    snowFront: 20,
    snowGusts: 0,
    glassBeads: 0,
    glassRivulets: 0,
    lightningBranches: 1,
    lightningForks: 0,
    lightningGlow: 0.64,
    flags: {
      stars: true,
      motes: false,
      layeredClouds: false,
      frontCloudBank: false,
      deepOvercast: false,
      distantCurtains: false,
      texturedCurtains: false,
      glassOverlay: false,
      glassDroplets: false,
      frostOverlay: false,
      lightningForks: false,
      relightAnchors: false,
      horizonPoles: false,
      multiFlash: false,
    },
  },
  lite: {
    resolutionScale: 0.82,
    maxDevicePixelRatio: 1,
    maxPixelCount: 760_000,
    frameIntervalMs: 1000 / 30,
    slowPassIntervalMs: 250,
    stars: 16,
    motes: 2,
    cloudLayers: 1,
    cloudSprites: 4,
    frontCloudSprites: 0,
    fogWisps: 2,
    frontMistWisps: 1,
    anchorBands: 2,
    scudLayers: 1,
    shadowPasses: 1,
    horizonGlowPasses: 1,
    rainBack: 36,
    rainFront: 24,
    rainCurtains: 1,
    curtainTextures: 0,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 0,
    snowBack: 28,
    snowFront: 28,
    snowGusts: 1,
    glassBeads: 0,
    glassRivulets: 0,
    lightningBranches: 1,
    lightningForks: 0,
    lightningGlow: 0.72,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: false,
      deepOvercast: false,
      distantCurtains: true,
      texturedCurtains: false,
      glassOverlay: false,
      glassDroplets: false,
      frostOverlay: false,
      lightningForks: false,
      relightAnchors: false,
      horizonPoles: false,
      multiFlash: false,
    },
  },
  standard: {
    resolutionScale: 0.9,
    maxDevicePixelRatio: 1.15,
    maxPixelCount: 980_000,
    frameIntervalMs: 1000 / 30,
    slowPassIntervalMs: 180,
    stars: 24,
    motes: 4,
    cloudLayers: 2,
    cloudSprites: 5,
    frontCloudSprites: 0,
    fogWisps: 2,
    frontMistWisps: 1,
    anchorBands: 3,
    scudLayers: 1,
    shadowPasses: 2,
    horizonGlowPasses: 2,
    rainBack: 52,
    rainFront: 32,
    rainCurtains: 1,
    curtainTextures: 0,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 1,
    snowBack: 40,
    snowFront: 36,
    snowGusts: 1,
    glassBeads: 3,
    glassRivulets: 1,
    lightningBranches: 1,
    lightningForks: 1,
    lightningGlow: 0.9,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: false,
      deepOvercast: true,
      distantCurtains: true,
      texturedCurtains: false,
      glassOverlay: true,
      glassDroplets: true,
      frostOverlay: false,
      lightningForks: true,
      relightAnchors: true,
      horizonPoles: true,
      multiFlash: false,
    },
  },
  cinematic: {
    resolutionScale: 1,
    maxDevicePixelRatio: 1.3,
    maxPixelCount: 1_280_000,
    frameIntervalMs: 1000 / 36,
    slowPassIntervalMs: 120,
    stars: 34,
    motes: 6,
    cloudLayers: 2,
    cloudSprites: 6,
    frontCloudSprites: 0,
    fogWisps: 3,
    frontMistWisps: 2,
    anchorBands: 4,
    scudLayers: 1,
    shadowPasses: 2,
    horizonGlowPasses: 3,
    rainBack: 72,
    rainFront: 40,
    rainCurtains: 2,
    curtainTextures: 1,
    contactBands: 0,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 0,
    shadowSweepPasses: 0,
    distortionPasses: 1,
    snowBack: 56,
    snowFront: 44,
    snowGusts: 2,
    glassBeads: 5,
    glassRivulets: 2,
    lightningBranches: 1,
    lightningForks: 1,
    lightningGlow: 1,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: false,
      deepOvercast: true,
      distantCurtains: true,
      texturedCurtains: true,
      glassOverlay: true,
      glassDroplets: true,
      frostOverlay: false,
      lightningForks: true,
      relightAnchors: true,
      horizonPoles: true,
      multiFlash: false,
    },
  },
};

export function getQualityBudget(quality: WeatherEffectsQuality): WeatherQualityBudget {
  return WEATHER_QUALITY_BUDGETS[quality];
}
