import type { WeatherEffectsQuality } from "../types";

export interface WeatherQualityFlags {
  stars: boolean;
  motes: boolean;
  layeredClouds: boolean;
  frontCloudBank: boolean;
  deepOvercast: boolean;
  distantCurtains: boolean;
  texturedCurtains: boolean;
  glassOverlay: boolean;
  glassDroplets: boolean;
  frostOverlay: boolean;
  lightningForks: boolean;
  relightAnchors: boolean;
  horizonPoles: boolean;
  multiFlash: boolean;
}

export interface WeatherQualityBudget {
  resolutionScale: number;
  maxDevicePixelRatio: number;
  maxPixelCount: number;
  stars: number;
  motes: number;
  cloudLayers: number;
  cloudSprites: number;
  frontCloudSprites: number;
  fogWisps: number;
  frontMistWisps: number;
  anchorBands: number;
  scudLayers: number;
  shadowPasses: number;
  horizonGlowPasses: number;
  rainBack: number;
  rainFront: number;
  rainCurtains: number;
  curtainTextures: number;
  contactBands: number;
  impactBursts: number;
  runoffSheets: number;
  accumulationBands: number;
  condensationBlooms: number;
  fogCreepBands: number;
  shadowSweepPasses: number;
  distortionPasses: number;
  snowBack: number;
  snowFront: number;
  snowGusts: number;
  glassBeads: number;
  glassRivulets: number;
  lightningBranches: number;
  lightningForks: number;
  lightningGlow: number;
  flags: WeatherQualityFlags;
}

export const WEATHER_QUALITY_BUDGETS: Record<WeatherEffectsQuality, WeatherQualityBudget> = {
  performance: {
    resolutionScale: 0.8,
    maxDevicePixelRatio: 1.05,
    maxPixelCount: 650_000,
    stars: 12,
    motes: 4,
    cloudLayers: 1,
    cloudSprites: 4,
    frontCloudSprites: 0,
    fogWisps: 2,
    frontMistWisps: 1,
    anchorBands: 1,
    scudLayers: 0,
    shadowPasses: 1,
    horizonGlowPasses: 1,
    rainBack: 52,
    rainFront: 104,
    rainCurtains: 1,
    curtainTextures: 0,
    contactBands: 1,
    impactBursts: 0,
    runoffSheets: 0,
    accumulationBands: 0,
    condensationBlooms: 0,
    fogCreepBands: 1,
    shadowSweepPasses: 0,
    distortionPasses: 0,
    snowBack: 34,
    snowFront: 64,
    snowGusts: 1,
    glassBeads: 0,
    glassRivulets: 0,
    lightningBranches: 1,
    lightningForks: 0,
    lightningGlow: 0.72,
    flags: {
      stars: true,
      motes: false,
      layeredClouds: false,
      frontCloudBank: false,
      deepOvercast: false,
      distantCurtains: true,
      texturedCurtains: false,
      glassOverlay: false,
      glassDroplets: false,
      frostOverlay: false,
      lightningForks: false,
      relightAnchors: false,
      horizonPoles: false,
      multiFlash: false,
    },
  },
  lite: {
    resolutionScale: 0.9,
    maxDevicePixelRatio: 1.2,
    maxPixelCount: 1_000_000,
    stars: 24,
    motes: 10,
    cloudLayers: 2,
    cloudSprites: 6,
    frontCloudSprites: 1,
    fogWisps: 4,
    frontMistWisps: 1,
    anchorBands: 1,
    scudLayers: 1,
    shadowPasses: 1,
    horizonGlowPasses: 1,
    rainBack: 88,
    rainFront: 168,
    rainCurtains: 2,
    curtainTextures: 1,
    contactBands: 1,
    impactBursts: 2,
    runoffSheets: 1,
    accumulationBands: 1,
    condensationBlooms: 1,
    fogCreepBands: 1,
    shadowSweepPasses: 0,
    distortionPasses: 0,
    snowBack: 68,
    snowFront: 124,
    snowGusts: 1,
    glassBeads: 0,
    glassRivulets: 0,
    lightningBranches: 1,
    lightningForks: 0,
    lightningGlow: 0.86,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: false,
      deepOvercast: false,
      distantCurtains: true,
      texturedCurtains: false,
      glassOverlay: true,
      glassDroplets: false,
      frostOverlay: true,
      lightningForks: false,
      relightAnchors: true,
      horizonPoles: false,
      multiFlash: false,
    },
  },
  standard: {
    resolutionScale: 0.98,
    maxDevicePixelRatio: 1.45,
    maxPixelCount: 1_600_000,
    stars: 40,
    motes: 16,
    cloudLayers: 3,
    cloudSprites: 9,
    frontCloudSprites: 2,
    fogWisps: 6,
    frontMistWisps: 2,
    anchorBands: 2,
    scudLayers: 1,
    shadowPasses: 2,
    horizonGlowPasses: 2,
    rainBack: 136,
    rainFront: 256,
    rainCurtains: 3,
    curtainTextures: 2,
    contactBands: 2,
    impactBursts: 4,
    runoffSheets: 1,
    accumulationBands: 1,
    condensationBlooms: 2,
    fogCreepBands: 2,
    shadowSweepPasses: 1,
    distortionPasses: 1,
    snowBack: 108,
    snowFront: 192,
    snowGusts: 2,
    glassBeads: 8,
    glassRivulets: 4,
    lightningBranches: 2,
    lightningForks: 1,
    lightningGlow: 0.96,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: false,
      deepOvercast: true,
      distantCurtains: true,
      texturedCurtains: true,
      glassOverlay: true,
      glassDroplets: false,
      frostOverlay: true,
      lightningForks: true,
      relightAnchors: true,
      horizonPoles: false,
      multiFlash: false,
    },
  },
  cinematic: {
    resolutionScale: 1.06,
    maxDevicePixelRatio: 1.7,
    maxPixelCount: 2_200_000,
    stars: 72,
    motes: 24,
    cloudLayers: 4,
    cloudSprites: 12,
    frontCloudSprites: 3,
    fogWisps: 9,
    frontMistWisps: 3,
    anchorBands: 3,
    scudLayers: 2,
    shadowPasses: 3,
    horizonGlowPasses: 2,
    rainBack: 208,
    rainFront: 384,
    rainCurtains: 4,
    curtainTextures: 3,
    contactBands: 3,
    impactBursts: 8,
    runoffSheets: 3,
    accumulationBands: 2,
    condensationBlooms: 4,
    fogCreepBands: 3,
    shadowSweepPasses: 1,
    distortionPasses: 1,
    snowBack: 164,
    snowFront: 288,
    snowGusts: 3,
    glassBeads: 16,
    glassRivulets: 7,
    lightningBranches: 3,
    lightningForks: 2,
    lightningGlow: 1.08,
    flags: {
      stars: true,
      motes: true,
      layeredClouds: true,
      frontCloudBank: true,
      deepOvercast: true,
      distantCurtains: true,
      texturedCurtains: true,
      glassOverlay: true,
      glassDroplets: true,
      frostOverlay: true,
      lightningForks: true,
      relightAnchors: true,
      horizonPoles: true,
      multiFlash: true,
    },
  },
};

export function getQualityBudget(quality: WeatherEffectsQuality): WeatherQualityBudget {
  return WEATHER_QUALITY_BUDGETS[quality];
}
